# backend:
#   name: git-gateway
#   branch: main # Branch to update (optional; defaults to master)

# # This line should *not* be indented
# media_folder: "/images/" # Media files will be stored in the repo under images/uploads

# publish_mode: editorial_workflow

# collections:
#   - name: "blog" # Used in routes, e.g., /admin/collections/blog
#     label: "Blog" # Used in the UI
#     folder: "src/content/blog" # The path to the folder where the documents are stored
#     create: true # Allow users to create new documents in this collection
#     slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
#     fields: # The fields for each document, usually in front matter
#       # - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
#       - { label: "Title", name: "title", widget: "string" }
#       - { label: "Description", name: "description", widget: "text" }
#       - { label: "Publish Date", name: "date", widget: "datetime" }
#       # - { label: "Publish Date", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD" }
#       - { label: "Blog Category", name: "blogCategory", widget: "select", options: ["Publication Updates", "News", "Lab Articles", "Others"], default: ["Lab Articles"], hint: "Select a category for the blog post" }
#       - { label: "Author", name: "pubBy", widget: "string" }
#       - { label: "Featured Image", name: "image", widget: "image" }
#       - { label: "Tags", name: "blogTags", widget: "select", multiple: true, allow_add: true, ["icdcece-2022", "conference-paper", "wireless-communication-technology", "cyber-physical-systems", "feature-selection", "machine-learning" ], hint: "Select relevant tags from the list or add your own tag. Make sure that tags should not have capital case and space, it can be '-'(hyphen) separated." }
#       - { label: "Read Time", name: "readTime", widget: "string", hint: "Estimated reading time, e.g., '5 min'" }

#       # - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
#       - { label: "Body", name: "body", widget: "markdown", hint: "Main content of the blog post" }


#       # - { label: "Featured Image", name: "heroImage", widget: "image" , hint: "Main image for the blog post" }
#       # - { label: "Blog Card Image", name: "blogCardImage", widget: "object", fields: [
#       #     { label: "Image Source", name: "src", widget: "image", hint: "The image to display on the blog card" },
#       #     { label: "Alt Text", name: "alt", widget: "string", hint: "Image description for accessibility" }
#       #   ]}
      
#       # - { label: "Tags", name: "blogTags", widget: "tagsSelect", multiple: true, hint: "Select relevant tags from the list or add your own tag." }

#   - name: "newslist"
#     label: "News List"
#     folder: "src/content/newslist"
#     create: true
#     slug: "{{slug}}"
#     fields:
#       - { name: "title", label: "Title", widget: "string", required: false }
#       - { name: "meta_title", label: "Meta Title", widget: "string", required: false }
#       - { name: "description", label: "Description", widget: "text", required: false }
#       - { name: "date", label: "Date", widget: "datetime" }
#       - { name: "text", label: "Text", widget: "text" }
#       - { name: "href", label: "Link", widget: "string", pattern: ["https?://.*", "Must be a valid URL"] }
#       - { name: "draft", label: "Draft", widget: "boolean", default: false }

# backend:
#   name: git-gateway
#   branch: main # Branch to update (optional; defaults to master)

# media_folder: "/images/" # Media files will be stored in the repo under images/uploads

# publish_mode: editorial_workflow

# collections:
#   - name: "blog" # Used in routes, e.g., /admin/collections/blog
#     label: "Blog" # Used in the UI
#     folder: "src/content/blog" # The path to the folder where the documents are stored
#     create: true # Allow users to create new documents in this collection
#     slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
#     fields: # The fields for each document, usually in front matter
#       - { label: "Title", name: "title", widget: "string" }
#       - { label: "Description", name: "description", widget: "text" }
#       - { label: "Publish Date", name: "date", widget: "datetime" }
#       - { label: "Blog Category", name: "blogCategory", widget: "select", options: ["Publication Updates", "News", "Lab Articles", "Others"], default: ["Lab Articles"], hint: "Select a category for the blog post" }
#       - { label: "Author", name: "pubBy", widget: "string" }
#       - { label: "Featured Image", name: "image", widget: "image" }
#       - { label: "Tags", name: "blogTags", widget: "select", multiple: true, allow_add: true, options: ["icdcece-2022", "conference-paper", "wireless-communication-technology", "cyber-physical-systems", "feature-selection", "machine-learning"], hint: "Select relevant tags from the list or add your own tag. Make sure that tags should not have capital case and space, it can be '-'(hyphen) separated." }
#       - { label: "Read Time", name: "readTime", widget: "string", hint: "Estimated reading time, e.g., '5 min'" }
#       - { label: "Body", name: "body", widget: "markdown", hint: "Main content of the blog post" }

#   - name: "newslist"
#     label: "News List"
#     folder: "src/content/newslist"
#     create: true
#     slug: "{{slug}}"
#     fields:
#       - { name: "title", label: "Title", widget: "string", required: false }
#       - { name: "meta_title", label: "Meta Title", widget: "string", required: false }
#       - { name: "description", label: "Description", widget: "text", required: false }
#       - { name: "date", label: "Date", widget: "datetime" }
#       - { name: "text", label: "Text", widget: "text" }
#       - { name: "href", label: "Link", widget: "string", pattern: ["https?://.*", "Must be a valid URL"] }
#       - { name: "draft", label: "Draft", widget: "boolean", default: false }


backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "/images/" # Media files will be stored in the repo under images/uploads

publish_mode: editorial_workflow

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Admin" }
      - { label: "Categories", name: "categories", widget: "list", default: ["others"] }
      - { label: "Tags", name: "tags", widget: "list", default: ["others"] }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "newslist"
    label: "News List"
    folder: "src/content/newslist"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "Title", label: "Title", widget: "string" }
      - { name: "Meta Title", label: "Meta Title", widget: "string", required: false }
      - { name: "Description", label: "Description", widget: "text", required: false }
      - { name: "Date", label: "Date", widget: "datetime" }
      - { name: "Text", label: "Text", widget: "text" }
      - { name: "Link", label: "Link", widget: "string", pattern: ["https?://.*", "Must be a valid URL"] }
      - { name: "Draft", label: "Draft", widget: "boolean", default: false }

  - name: "authors"
    label: "Authors"
    folder: "src/content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "Title", label: "Title", widget: "string" }
      - { name: "Meta Title", label: "Meta Title", widget: "string", required: false }
      - { name: "Email", label: "Email", widget: "string", required: false }
      - { name: "Image", label: "Image", widget: "image", required: false }
      - { name: "Description", label: "Description", widget: "text", required: false }
      - { name: "Social", label: "Social Links", widget: "list", fields: [
          { name: "name", label: "Name", widget: "string", required: false },
          { name: "icon", label: "Icon", widget: "string", required: false },
          { name: "link", label: "Link", widget: "string", required: false }
        ] }
      - { name: "Draft", label: "Draft", widget: "boolean", required: false }

  - name: "people"
    label: "People"
    folder: "src/content/people"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "Title", label: "Title", widget: "string" }
      - { name: "Meta Title", label: "Meta Title", widget: "string", required: false }
      - { name: "Email", label: "Email", widget: "string", required: false }
      - { name: "Image", label: "Image", widget: "image", required: false }
      - { name: "Designation", label: "Designation", widget: "string", required: false }
      - { name: "Qualification", label: "Qualification", widget: "string", required: false }
      - { name: "Description", label: "Description", widget: "text", required: false }
      - { name: "Category", label: "Category", widget: "string" }
      - { name: "Section", label: "Section", widget: "string", required: false }
      - { name: "Social", label: "Social Links", widget: "list", fields: [
          { name: "name", label: "Name", widget: "string", required: false },
          { name: "icon", label: "Icon", widget: "string", required: false },
          { name: "link", label: "Link", widget: "string", required: false }
        ] }
      - { name: "Draft", label: "Draft", widget: "boolean", required: false }

  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "Title", label: "Title", widget: "string" }
      - { name: "Meta Title", label: "Meta Title", widget: "string", required: false }
      - { name: "Description", label: "Description", widget: "text", required: false }
      - { name: "Image", label: "Image", widget: "image", required: false }
      - { name: "Draft", label: "Draft", widget: "boolean", required: false }
      